# Generated by Django 4.2.7 on 2023-11-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UniversityQuizApplication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Examiner", "Examiner"), ("Examinee", "Examinee")],
                default="Examinee",
                max_length=8,
            ),
        ),
    ]
