# Generated by Django 4.2.7 on 2023-11-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UniversityQuizApplication", "0002_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutorizeMailerDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("mail_domain_name", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Authorize Domain",
            },
        ),
    ]
