# Generated by Django 4.2.7 on 2023-11-08 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UniversityQuizApplication", "0003_autorizemailerdomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("modifiedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("total_mark", models.IntegerField(blank=True, default=0, null=True)),
                ("no_of_questions", models.PositiveBigIntegerField(default=0)),
                ("quiz_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("modifiedDate", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_category",
                        to="UniversityQuizApplication.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "correct_answer",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "questions_marks",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True, null=True, upload_to="quiz_question/images/"
                    ),
                ),
                (
                    "audio_tracks",
                    models.FileField(
                        blank=True, null=True, upload_to="quiz_question/audio_tracks/"
                    ),
                ),
                (
                    "video_tracks",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="quiz_question/video_tracks/",
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("text", "TEXT"),
                            ("audio", "AUDIO"),
                            ("video", "VIDEO"),
                            ("image", "IMAGE"),
                        ],
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("modifiedDate", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_question_quiz",
                        to="UniversityQuizApplication.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizOptionsCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("options", models.TextField(blank=True, max_length=1000, null=True)),
                ("correct_flag", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("modifiedDate", models.DateTimeField(auto_now=True)),
                (
                    "quiz_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_question_option",
                        to="UniversityQuizApplication.quizquestion",
                    ),
                ),
            ],
        ),
    ]
