# Generated by Django 4.2.7 on 2023-11-08 01:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "UniversityQuizApplication",
            "0004_category_quiz_quizquestion_quizoptionscreator",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizoptionscreator",
            old_name="options",
            new_name="option",
        ),
    ]
