# Generated by Django 4.2.7 on 2023-11-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UniversityQuizApplication", "0009_category_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz_time",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
